[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Jay Kruer <jaykruer@posteo.de>"]
edition = "2018"

[dependencies]
bit-vec = "0.6.1"
itertools = "0.8.0"
openssl = "0.10.23"
base64 = "0.10.1"
rand = "0.8.0"
